[versions]
activityCompose = "1.13.0"
composeBom = "2026.06.01"
coroutines = "1.10.2"
lifecycle = "2.10.0"
jgit = "7.6.0.202603022253-r"
tesseract = "4.9.0"
javascriptEngine = "1.1.0"
shizuku = "13.1.5"
documentFile = "1.1.0"
room = "2.8.4"
work = "2.11.2"
webkit = "1.16.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
tesseract = { module = "cz.adaptech.tesseract4android:tesseract4android", version.ref = "tesseract" }
androidx-javascriptengine = { module = "androidx.javascriptengine:javascriptengine", version.ref = "javascriptEngine" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentFile" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
